from django.db import models

from utils.models import BaseModel
from django.conf import settings


class Movie(BaseModel):
    title = models.CharField(max_length=255, help_text="Title of the movie.")
    year = models.PositiveIntegerField(help_text="Releasing year of the movie.")
    imdb_rating = models.FloatField(help_text="Rating will be between 1 to 10.", null=True, blank=True)
    rating_user_count = models.PositiveBigIntegerField(help_text="Rating based on how many users.")
    featured_poster = models.URLField(null=True, blank=True)
    imdb_source_url = models.URLField(unique=True, help_text="Unique URL of movie generated by imdb.")

    def __str__(self):
        return "%s (%s)" % (self.title, self.year)


class WatchLaterList(BaseModel):
    movie = models.ForeignKey(Movie, related_name='watch_later_list', on_delete=models.CASCADE)
    has_watched = models.BooleanField(default=False)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='watch_later_list', on_delete=models.CASCADE)

    class Meta:
        # One unique user can add one unique movie in the watch later list only once.
        unique_together = ('movie', 'user')
